# Generated by Django 5.1.2 on 2024-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProject', '0003_student_password_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session_token',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
