# Generated by Django 4.2.7 on 2024-11-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProject', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='def', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
